# Generated by Django 3.0.5 on 2020-04-17 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webpage',
            old_name='top',
            new_name='topic',
        ),
    ]
