# Generated by Django 3.0.5 on 2020-04-17 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20200417_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='top_name',
            new_name='name',
        ),
    ]
